# Generated by Django 3.1.6 on 2021-03-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20210219_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Вакансия(ю)', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
