# Generated by Django 3.1.6 on 2021-03-22 16:18

from django.db import migrations, models
import scraping.models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_auto_20210318_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errors',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='url',
            name='url_data',
            field=models.JSONField(default=scraping.models.default_urls),
        ),
    ]
