# Generated by Django 3.1.6 on 2021-03-23 13:34

from django.db import migrations
import jsonfield.fields
import scraping.models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_auto_20210322_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errors',
            name='data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='url',
            name='url_data',
            field=jsonfield.fields.JSONField(default=scraping.models.default_urls),
        ),
    ]
